# Common properties shared across all profiles
spring:
  application:
    name: ubk
  profiles:
    active: dev # Default profile is 'dev'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Common app properties (can be overridden by profiles)
app:
  scheduler:
    monthly-verification:
      enabled: false
    recalculation:
      enabled: false
    payment:
      enabled: false
    data-sync:
      enabled: false

  rate-limiting:
    enabled: true
    cache-name: "rate-limit-buckets"
    rules:
      - bandwidth:
          - capacity: 100
            time: 1
            unit: minutes
        url-pattern: "/api/**"
